export const topicToTagMap: Record<string, string[]> = {
  "dynamic programming": ["dp"],
  dp: ["dp"],
  graphs: ["graphs"],
  "graph theory": ["graphs"],
  greedy: ["greedy"],
  math: ["math"],
  "data structures": ["data structures"],
  "binary search": ["binary search"],
  bitmask: ["bitmasks"],
  bitmasks: ["bitmasks"],
  "brute force": ["brute force"],
  "number theory": ["number theory"],
  strings: ["strings"],
  string: ["strings"],
  trees: ["trees"],
  tree: ["trees"],
  "shortest path": ["shortest paths"],
  "shortest paths": ["shortest paths"],
  "divide and conquer": ["divide and conquer"],
  "two pointers": ["two pointers"],
  combinatorics: ["combinatorics"],
  "constructive algorithms": ["constructive algorithms"],
  dfs: ["dfs and similar"],
  "dfs and similar": ["dfs and similar"],
  dsu: ["dsu"],
  "expression parsing": ["expression parsing"],
  fft: ["fft"],
  flows: ["flows"],
  games: ["games"],
  geometry: ["geometry"],
  "graph matchings": ["graph matchings"],
  hashing: ["hashing"],
  implementation: ["implementation"],
  interactive: ["interactive"],
  matrices: ["matrices"],
  "meet-in-the-middle": ["meet-in-the-middle"],
  probabilities: ["probabilities"],
  schedules: ["schedules"],
  sortings: ["sortings"],
  "string suffix structures": ["string suffix structures"],
  "ternary search": ["ternary search"],
  // Add more mappings as needed
};
