services:
  - type: web
    name: cf-contest-analyser-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true

  - type: worker
    name: cf-contest-analyser-worker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_GENAI_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false
    autoDeploy: true 